config/routes.rb
Rails.application.routes.draw do

  # Deviseのログイン画面をrootに設定、そのままだと設定できないので、devise＿scopeを使用
  devise_scope :user do
    root to: 'users/sessions#new'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    resources :tasks
    get '/tasks_all_incomplete', to: 'tasks#tasks_all_incomplete'
    get '/tasks_all_history', to: 'tasks#tasks_all_history'
    resources :tasks_request
    get '/tasks_request_all_history', to: 'tasks_request#tasks_request_all_history'
    get '/tasks_request_reply', to: 'tasks_request#tasks_request_reply'
    patch '/update_tasks_request_reply', to: 'tasks_request#update_tasks_request_reply'
    get '/tasks_request_reply_confirm', to: 'tasks_request#tasks_request_reply_confirm'
  end

  resources :events
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, uniqueness: true
  validates :task_status, presence: true
  validates :progress, presence: true
  validates :start, presence: true
  validates :end_at, presence: true

  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end_at == self.end_at.midnight ? true : false
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_user_user_id, only: %i[index new create edit show tasks_all_history update_tasks_request tasks_all_incomplete]
  before_action :set_task_id, only: %i[edit show update destroy]

  #タスク一覧(押下ボタン毎でタスクを取得)
  def index
    if params[:btn_status] == 'completed'
      @btn_status = 'completed'
      tasks = @user.tasks.where(task_status: '完了')
      request_tasks = Task.where('(request_reply = ?) AND (contractor = ?) AND (task_status = ?)', '承諾', @user.id, '完了')
      if request_tasks.present?
        @tasks = Task.where(id: (tasks + request_tasks).map(&:id)).order(end_ta: :DESC).page(params[:page]).per(10)
      else
        @tasks = tasks.order("end_at DESC").page(params[:page]).per(10)
      end
    else
      @btn_status = 'incomplete'
      tasks = @user.tasks.where(task_status: '未完了').where.not(client: @user.id)
      request_tasks = Task.where('(request_reply = ?) AND (contractor = ?) AND (task_status = ?)', '承諾', @user.id, '未完了')
      tasks_id = (tasks + request_tasks).map(&:id)
      if tasks.present? || request_tasks.present?
        @tasks = Task.where(id: tasks_id).order(:end_at).page(params[:page]).per(5)
      elsif tasks.present?
        @tasks = tasks.order("end_at").page(params[:page]).per(5)
      else
        @tasks = tasks
      end

      # tasks = @user.tasks.where(task_status: '未完了').where.not(client: @user.id)
      # request_tasks = Task.where('(request_reply = ?) AND (contractor = ?) AND (task_status = ?)', '承諾', @user.id, '未完了')
      # if request_tasks.present?
      #   @tasks = Task.where(id: (tasks + request_tasks).map(&:id)).order("end").page(params[:page]).per(5)
      # else
      #   @tasks = tasks.order("end").page(params[:page]).per(5)
      # end
    end
    @request_tasks = Task.where('(request_reply = ?) AND (contractor = ?)', '未返答', @user.id) # タスク依頼アラート
    @reply_tasks = @user.tasks.where(reply_confirm: false).where('(request_reply = ?) OR (request_reply = ?)', '承諾', '拒否') # タスク返信アラート
  end

  def new
    @task = Task.new
  end

  def create
    @task = @user.tasks.build(tasks_create_params)
    if @task.save
      flash[:notice] = 'タスクを新規登録しました。'
    else
      flash[:alert] = 'タスクの新規登録に失敗しました。'
    end
    redirect_to user_tasks_path(@user)
  end

  def edit
    @btn_status = params[:btn_status]
    @users = User.all.where.not(id: @user.id)
  end

  def show
    if (@task.client != 0) && (@task.user_id != @user.id)
      @client = User.find(@task.client)
    elsif (@task.client != 0) && (@task.user_id == @user.id)
      @contractor = User.find(@task.contractor)
    end
  end

  def update
    if (current_user.id != @task.user_id) && (current_user.id != @task.contractor)
      @task.destroy
      if current_user.tasks.create(tasks_update_params)
        flash[:notice] = 'タスクを新規登録しました。'
      else
        flash[:alert] = 'タスクの新規登録に失敗しました。'
      end
    end
    if (current_user.id == @task.user_id) || (current_user.id == @task.contractor)
      if @task.update(tasks_update_params)
        flash[:notice] = 'タスク情報を更新しました。'
      else
        flash[:alert] = 'タスク情報の更新に失敗しました。'
      end
    end
    redirect_to user_tasks_path(current_user.id)
  end

  def destroy
    @task.destroy
    flash[:notice] = "#{@task.title}のタスクデータを削除しました。"
    redirect_to user_tasks_path(@task.user_id)
  end

  # タスク履歴一覧(タスク再登録用)
  def tasks_all_history
    @tasks =
      if params[:search].present?
        Task.where('name LIKE ?', "%#{params[:search]}%").where(task_status: '完了').order("user_id").page(params[:page]).per(10)
      else
        Task.where(task_status: '完了').page(params[:page]).order("user_id").per(10)
      end
  end

  def tasks_all_incomplete
    @tasks =
      if params[:search].present?
        Task.where('name LIKE ?', "%#{params[:search]}%").where(task_status: '未完了').where.not('(request_reply = ?) OR (request_reply = ?)', '未返信', '拒否').order("end_at").page(params[:page]).per(10)
      else
        Task.where(task_status: '未完了').where.not('(request_reply = ?) OR (request_reply = ?)', '未返信', '拒否').order("end_at").page(params[:page]).per(10)
      end
  end

  private

  def tasks_create_params
    params.require(:task).permit(:title, :details, :task_status, :progress, :start, :end_at)
  end

  def tasks_update_params
    params.require(:task).permit(:title, :details, :task_status, :progress, :start, :end_at)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
    <% if @btn_status != 'reregistration' %>
      <h5 class="modal-title">タスク情報編集</h5>
    <% else %>
      <h5 class="modal-title">タスク登録（履歴）</h5>
    <% end %>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_with(model: @task, url: user_task_path(@task.user_id, @task.id), local: true, method: :patch) do |f| %>
      <div class="modal-body">

        <% if (@task.client == 0) && (@user.id == @task.user_id) %>
          <div class="box-title">
            <%= f.label :title, "件名", class: "form-control-label" %>
            <%= f.text_field :title, class: "form-control", placeholder: "最大20文字", maxlength: 20, required: true %>
          </div>
        <% end %>

        <div class="box-details">
          <%= f.label :details, "詳細" %>
          <%= f.text_area :details, class: "form-control" %>
        </div>

        <% if (@task.client == 0) && (@user.id == @task.user_id) %>
          <div class="date-start-end">
            <div class="row">
              <div class="col-6 box-start">
                <%= f.label :start, "開始日（予定）" %>
                <div class="input-group date" id="datePicker-start" data-target-input="nearest">
                <%= f.text_field :start, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-start"}, required: true %>
                  <div class="input-group-append" data-target="#datePicker-start" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
              </div>
              <div class="col-6 box-end">
                <%= f.label :end_at, "完了日（予定）" %>
                <div class="input-group date" id="datePicker-end" data-target-input="nearest">
                <%= f.text_field :end_at, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-end"}, required: true %>
                  <div class="input-group-append" data-target="#datePicker-end" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="select-status-progress-request">
          <div class="box-task_status">
            <%= f.label :task_status, "状態" %>
            <%= f.select(:task_status, [["未完了", "未完了"], ["完了", "完了"]], {include_blank: "選択して下さい"}, class: 'form-control select', required: true) if @btn_status != 'reregistration' %>
            <%= f.select(:task_status, [["未完了", "未完了"], ["完了", "完了"]], {include_blank: "選択して下さい", selected: "未完了"}, class: 'form-control select', required: true) if @btn_status == 'reregistration' %>
          </div>
          <div class="box-progress">
            <%= f.label :progress, "進捗状況" %>
            <%= f.number_field :progress, min: 0, class: "form-control number", required: true if @btn_status != 'reregistration'  %>
            <%= f.number_field :progress, min: 0, :value => 0, class: "form-control number", required: true if @btn_status == 'reregistration' %>
          </div>
          <span class="align-self-center">%</span>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">
          キャンセル
        </button>
        <% if @btn_status != 'reregistration' %>
          <%= f.submit "変更する", class: "btn btn-primary btn-edit" %>
        <% else %>
          <%= f.submit "登録する", class: "btn btn-primary btn-edit" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_new.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">タスク新規登録</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_with(model: @task, url: user_tasks_path(@user), local: true, method: :post, id: "task-form") do |f| %>
      <div class="modal-body">
        <div class="box-title">
          <%= f.label :title, "件名", class: "form-control-label" %>
          <%= f.text_field :title, class: "form-control", placeholder: "最大20文字", maxlength: 20, required: true %>
        </div>

        <div class="box-details">
          <%= f.label :details, "詳細" %>
          <%= f.text_area :details, class: "form-control" %>
        </div>

        <div class="date-start-end">
          <div class="row">
            <div class="col-6 box-start">
              <%= f.label :start, "開始日（予定）" %>
              <div class="input-group date" id="datePicker-start" data-target-input="nearest">
              <%= f.text_field :start, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-start"}, required: true %>
                <div class="input-group-append" data-target="#datePicker-start" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
            </div>
            <div class="col-6 box-end">
              <%= f.label :end_at, "完了日（予定）" %>
              <div class="input-group date" id="datePicker-end" data-target-input="nearest">
              <%= f.text_field :end_at, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-end"}, required: true %>
                <div class="input-group-append" data-target="#datePicker-end" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="select-status-progress-request">
          <div class="box-task_status">
            <%= f.label :task_status, "状態" %>
            <%= f.select(:task_status, [["未完了", "未完了"], ["完了", "完了"]], {include_blank: "選択して下さい"}, class: 'form-control select', required: true) %>
          </div>
          <div class="box-progress">
            <%= f.label :progress, "進捗状況" %>
            <%= f.number_field :progress, min: 0, class: "form-control number", required: true %>
          </div>
          <span class="align-self-center">%</span>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">
          キャンセル
        </button>
          <%= f.submit "新規登録", class: "btn btn-primary btn-new", id: "task-create" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_show.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">タスク詳細</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_with(model: @task, url: user_task_path(@task.user_id, @task.id), local: true, method: :patch) do |f| %>
      <div class="modal-body">
        <div class="box-title">
          <%= f.label :title, "件名", class: "form-control-label" %>
          <%= f.text_field :title, class: "form-control", placeholder: "最大20文字", maxlength: 20, disabled: true %>
        </div>

        <div class="box-details">
          <%= f.label :details, "詳細" %>
          <%= f.text_area :details, class: "form-control", disabled: true %>
        </div>

          <div class="date-start-end">
            <div class="row">
              <div class="col-6 box-start">
                <%= f.label :start, "開始日（予定）" %>
                <div class="input-group date" id="datePicker-start" data-target-input="nearest">
                <%= f.text_field :start, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-start"}, disabled: true %>
                  <div class="input-group-append" data-target="#datePicker-start" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar" readonly="readonly"></i></div>
                  </div>
                </div>
              </div>
              <div class="col-6 box-end">
                <%= f.label :end_at, "完了日（予定）" %>
                <div class="input-group date" id="datePicker-end" data-target-input="nearest">
                <%= f.text_field :end_at, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-end"}, disabled: true %>
                  <div class="input-group-append" data-target="#datePicker-end" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar" readonly="readonly"></i></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        <div class="select-status-progress-request">
          <div class="box-task_status">
            <%= f.label :task_status, "状態" %>
            <%= f.select(:task_status, [["未完了", "未完了"], ["完了", "完了"]], {include_blank: "選択して下さい"}, class: 'form-control select', disabled: true) %>
          </div>
          <div class="box-progress">
            <%= f.label :progress, "進捗状況" %>
            <%= f.number_field :progress, min: 0, class: "form-control number", disabled: true %>
          </div>
          <span class="align-self-center">%</span>
          <% if @client.present? %>
            <div class="box-request">
              <%= f.label :user_id, "依頼主" %>
              <%= f.select(:client, [["#{@client.name}", "#{@client.id}"], ["#{@client.name}", "#{@client.id}"]], {include_blank: "選択して下さい"}, class: 'form-control', disabled: true) %>
            </div>
          <% elsif @contractor.present? %>
            <div class="box-request">
              <%= f.label :user_id, "依頼先" %>
              <%= f.select(:contractor, [["#{@contractor.name}", "#{@contractor.id}"], ["#{@contractor.name}", "#{@contractor.id}"]], {include_blank: "選択して下さい"}, class: 'form-control', disabled: true) %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">
          戻る
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_tasks_all_incomplete_table.html.erb
<table class="table table-condensed table-hover" id="table-users">
  <thead>
    <tr>
      <th>依頼主</th>
      <th>件名</th>
      <th>開始日（予定）</th>
      <th>完了日（予定）</th>
      <th>進捗状況</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task|%>
      <tr>
        <td><%= User.find(task.client).name if task.client != 0 %></td>
        <td><%= task.title %></td>
        <td><%= l(task.start, format: :long) %></td>
        <td><%= l(task.end_at, format: :long) %></td>
        <td><%= task.progress %>%</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/_tasks_table.html.erb
<tbody>
  <tr>
    <td><%= User.find(task.client).name if task.client != 0 %></td>
    <td><%= task.title %></td>
    <td><%= l(task.start, format: :long) %></td>
    <td><%= l(task.end_at, format: :long) %></td>
    <td><%= task.progress %>%</td>
    <td>
      <div class="task-table-buns">
        <%= link_to "編集", edit_user_task_path(@user, task.id), remote: true, class: "btn btn-primary btn-sm" %>
        <% if (task.client == 0) || (@user.id == task.user_id) %>
          <%= link_to "削除", user_task_path(task.user_id, task.id), method: :delete,data: { confirm: "#{task.title}を削除してよろしいですか？" }, class: "btn btn-danger btn-sm" %>
        <% end %>
        <%= link_to "詳細", user_task_path(@user, task.id), remote: true, class: "btn btn-primary btn-sm" %>
      </div>
    </td>
  </tr>
</tbody>

app/views/tasks/edit.js.erb
$("#task-edit").html("<%= escape_javascript(render 'edit') %>");
$("#task-edit").modal("show");

$(document).ready(function () {
  $('#datePicker-start').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
  $('#datePicker-end').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
});

app/views/tasks/index.html.erb
<% provide(:title, "All_tasks") %>
<div class="tasks-container container-fluid">
  <% if @btn_status == 'completed'%>
    <div class="title"><h1>タスク一覧（完了）</h1></div>
  <% else %>
    <div class="title"><h1>タスク一覧（未完了）</h1></div>
  <% end %>
  <div class="row">
    <div class="task-btn">
      <div class="task-btns-inc-com">
        <%= link_to "タスク登録（新規）", new_user_task_path(@user), remote: true, class: "btn btn-primary btn-sm" %>
        <%= link_to "タスク登録（履歴）", user_tasks_all_history_path(@user), class: "btn btn-primary btn-sm" %>
        <%= link_to "未完了", user_tasks_path(@user, btn_status: "incomplete"), class: "btn btn-primary btn-sm" %>
        <%= link_to "完了", user_tasks_path(@user, btn_status: "completed"), class: "btn btn-primary btn-sm" %>
        <% if current_user.admin? %>
          <%= link_to "依頼", user_tasks_request_index_path(@user), class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
      <div class="request-related-info">
        <% if @request_tasks.count !=0 %>
          <%= link_to "・依頼されたタスクが #{@request_tasks.count}件あります。", user_tasks_request_reply_path(@user), remote: true, class: "request-alert" %>
        <% end %>
        <% if @reply_tasks.count !=0 %>
          <%= link_to "・依頼していたタスクに #{@reply_tasks.count}件の返信があります。", user_tasks_request_reply_confirm_path(@user), remote: true, class: "request-alert" %>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-condensed table-hover" id="table-users">
        <thead>
          <tr>
            <th>依頼主</th>
            <th>件名</th>
            <th>開始日（予定）</th>
            <th>完了日（予定）</th>
            <th>進捗状況</th>
            <th></th>
          </tr>
        </thead>
        <% if @tasks.present? %>
          <%= render partial: 'tasks_table', collection: @tasks, as: :task %>
        <% end %>
      </table>
      <% if @tasks.blank?%>
        <div class="task-none">
          <a>該当のタスクはありません。</a>
        </div>
      <% end %>
      <% if @tasks.present?%>
        <div class="paginate">
          <%= paginate @tasks %>
        </div>
      <% end %>
      <% if @btn_status == 'incomplete'%>
        <div class='calendar'></div>
      <% end %>
    </div>
  </div>
</div>
<!--タスク情報編集用モーダルウインドウ表示-->
<div class="modal fade" id="task-edit" tabindex="-1" role="dialog" aria-labelledby="usereditModalLabel" aria-hidden="true"></div>
<!--タスク詳細用モーダルウインドウ表示-->
<div class="modal fade" id="task-show" tabindex="-1" role="dialog" aria-labelledby="usereditModalLabel" aria-hidden="true"></div>
<!--依頼されたタスクに返信用モーダルウインドウ表示-->
<div class="modal fade" id="tasks-request-reply" tabindex="-1" role="dialog" aria-labelledby="usereditModalLabel" aria-hidden="true"></div>
<!--依頼していたタスクの返信確認用モーダルウインドウ表示-->
<div class="modal fade" id="tasks_request_reply_confirm" tabindex="-1" role="dialog" aria-labelledby="usereditModalLabel" aria-hidden="true"></div>

app/views/tasks/new.js.erb
$("#task-new").html("<%= escape_javascript(render 'new') %>");
$("#task-new").modal("show");

$(document).ready(function () {
  $('#datePicker-start').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
  $('#datePicker-end').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
});

app/views/tasks/show.js.erb
$("#task-show").html("<%= escape_javascript(render 'show') %>");
$("#task-show").modal("show");

$(document).ready(function () {
  $('#datePicker-start').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
  $('#datePicker-end').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
});

app/views/tasks/tasks_all_history.html.erb
<% provide(:title, 'All_tasks_history') %>
<div class="tasks-container container-fluid">
  <div class="title">
    <% if params[:search].present? %>
      <h1>検索結果</h1>
    <% else %>
      <h1>タスク履歴（再登録）</h1>
    <% end %>
  </div>
  <div class="row">
    <div class="task-btn col-6">
      <div class="task-btns">
        <%= link_to "タスク登録（新規）", new_user_task_path(@user), remote: true, class: "btn btn-primary btn-sm" %>
        <%= link_to "未完了", user_tasks_path(@user, btn_status: "incomplete"), class: "btn btn-primary btn-sm" %>
        <%= link_to "完了", user_tasks_path(@user, btn_status: "completed"), class: "btn btn-primary btn-sm" %>
        <% if current_user.admin? %>
          <%= link_to "依頼", user_tasks_request_index_path(@user), class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div class="user-search float-right">
        <a id="search">タスク名検索</a>
        <%= form_with url: user_tasks_request_all_history_path(@user), method: :get, local: true do |form| %>
          <%= form.text_field :search, id: "search-box", placeholder: "キーワードを入力" %>
          <%= form.submit "検索", id: "search-btn", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-condensed table-hover" id="table-users">
        <thead>
          <tr>
            <th>件名</th>
            <th>詳細</th>
            <th>開始日（予定）</th>
            <th>完了日（予定）</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @tasks.each do |task| %>
            <tr>
              <td><%= task.title %></td>
              <td><%= task.details %></td>
              <td><%= task.start %></td>
              <td><%= task.end_at %></td>
              <td>
                <%= link_to "再登録", edit_user_task_path(task.user_id, task.id, btn_status: "reregistration"), remote: true, class: "btn btn-primary btn-sm float-right", id: "task-request-btn" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="users-paginate">
        <% if @tasks.present?%>
          <div class="paginate">
            <%= paginate @tasks %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--タスク情報編集用モーダルウインドウ表示-->
<div class="modal fade" id="task-edit" tabindex="-1" role="dialog" aria-labelledby="usereditModalLabel" aria-hidden="true"></div>

app/views/tasks/tasks_all_incomplete.html.erb
<% provide(:title, 'All_tasks_incomplete') %>
<div class="tasks-container container-fluid">
  <div class="title">
    <% if params[:search].present? %>
      <h1>検索結果</h1>
    <% else %>
      <h1>未完了タスク確認（全員）</h1>
    <% end %>
  </div>
  <div class="row">
    <div class="task-btn col-6">
      <div class="task-btns">
        <%= link_to "タスク登録（新規）", new_user_task_path(@user), remote: true, class: "btn btn-primary btn-sm" %>
        <%= link_to "タスク登録（履歴）", user_tasks_all_history_path(@user), class: "btn btn-primary btn-sm" %>
        <%= link_to "未完了", user_tasks_path(@user, btn_status: "incomplete"), class: "btn btn-primary btn-sm" %>
        <%= link_to "完了", user_tasks_path(@user, btn_status: "completed"), class: "btn btn-primary btn-sm" %>
        <% if current_user.admin? %>
          <%= link_to "依頼", user_tasks_request_index_path(@user), class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div class="user-search float-right">
        <a id="search">タスク名検索</a>
        <%= form_with url: user_tasks_request_all_history_path(@user), method: :get, local: true do |form| %>
          <%= form.text_field :search, id: "search-box", placeholder: "キーワードを入力" %>
          <%= form.submit "検索", id: "search-btn", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-condensed table-hover" id="table-users">
        <thead>
          <tr>
            <th>依頼主</th>
            <th>担当者</th>
            <th>件名</th>
            <th>詳細</th>
            <th>開始日（予定）</th>
            <th>完了日（予定）</th>
            <th>進捗度</th>
          </tr>
        </thead>
        <tbody>
          <% @tasks.each do |task| %>
            <tr>
              <td><%= User.find(task.client).name if task.client != 0 %></td>
              <td>
                <%= User.find(task.contractor).name if task.contractor != 0 %>
                <%= User.find(task.user.id).name if task.contractor == 0 %>
              </td>
              <td><%= task.title %></td>
              <td><%= task.details %></td>
              <td><%= task.start %></td>
              <td><%= task.end_at %></td>
              <td><%= task.progress %>%</td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="users-paginate">
        <% if @tasks.present?%>
          <div class="paginate">
            <%= paginate @tasks %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>