config/routes.rb
Rails.application.routes.draw do

  # Deviseのログイン画面をrootに設定、そのままだと設定できないので、devise＿scopeを使用
  devise_scope :user do
    root to: 'users/sessions#new'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users do
    resources :tasks
    get '/tasks_all_incomplete', to: 'tasks#tasks_all_incomplete'
    get '/tasks_all_history', to: 'tasks#tasks_all_history'
    resources :tasks_request
    get '/tasks_request_all_history', to: 'tasks_request#tasks_request_all_history'
    get '/tasks_request_reply', to: 'tasks_request#tasks_request_reply'
    patch '/update_tasks_request_reply', to: 'tasks_request#update_tasks_request_reply'
    get '/tasks_request_reply_confirm', to: 'tasks_request#tasks_request_reply_confirm'
  end

  resources :events
end

app/controllers/tasks_request_controller.rb
class TasksRequestController < ApplicationController
  before_action :set_user_user_id, only: %i[index create new edit show update destroy tasks_request_all_history tasks_request_reply update_tasks_request_reply tasks_request_reply_confirm]
  before_action :set_task_id, only: %i[edit show update destroy]

  # 依頼済タスク一覧(依頼確認編集用)
  def index
    @tasks =
      if params[:search].present?
        Task.where('name LIKE ?', "%#{params[:search]}%").where(client: @user.id).where(task_status: '未完了').order("end_at").page(params[:page]).per(10)
      else
        Task.where(client: @user.id).page(params[:page]).order("end_at").per(10)
      end
  end

  def create
    @task = @user.tasks.build(tasks_request_create_params)
    if @task.save
      flash[:notice] = 'タスクを新規依頼しました。'
    else
      flash[:alert] = 'タスクの新規依頼に失敗しました。'
    end
    redirect_to user_tasks_request_index_path(@user.id)
  end

  def new
    @task = Task.new
    @users = User.all.where.not(id: current_user.id)
  end

  def edit
    @btn_status = params[:btn_status]
    @users = User.all.where.not(id: current_user.id)
  end

  def show
    @contractor = User.find(@task.contractor)
  end

  def update
    if current_user.id != @task.user_id
      @task.destroy
      if current_user.tasks.create(tasks_request_update_params)
        flash[:notice] = 'タスクを新規依頼しました。'
      else
        flash[:alert] = 'タスクの新規依頼に失敗しました。'
      end
    end
    if current_user.id == @task.user_id
      if @task.update(tasks_request_update_params)
        flash[:notice] = '依頼中のタスク情報を更新しました。'
      else
        flash[:alert] = '依頼中のタスク情報更新に失敗しました。'
      end
    end
    redirect_to user_tasks_request_index_path(@user.id)
  end

  def destroy
    @task.destroy
    flash[:notice] = "#{@task.title}のタスクデータを削除しました。"
    redirect_to user_tasks_request_index_path(@user.id)
  end

  # タスク履歴一覧(タスク依頼用)
  def tasks_request_all_history
    @tasks =
      if params[:search].present?
        Task.where('title LIKE ?', "%#{params[:search]}%").where(task_status: '完了').page(params[:page]).per(10)
      else
        Task.where(task_status: '完了').page(params[:page]).per(10)
      end
  end

  # 依頼されたタスク表示用
  def tasks_request_reply
    @request_tasks = Task.where('(request_reply = ?) AND (contractor = ?)', '未返答', @user.id).order("end_at")
  end

  # 依頼されたタスクに対しての返信用
  def update_tasks_request_reply
    update_tasks_request_reply_params.each do |id, item|
      task = Task.find(id)
      if task.update(item)
        flash[:notice] = '依頼されたタスクに返信しました。'
      else
        flash[:alert] = '依頼されたタスクの返信に失敗しました。'
      end
    end
    redirect_to user_tasks_path(@user.id)
  end

  # 依頼したタスクに対しての返信確認用
  def tasks_request_reply_confirm
    @reply_tasks = @user.tasks.where(reply_confirm: false).where('(request_reply = ?) OR (request_reply = ?)', '承諾', '拒否').order("end_at")
    @reply_tasks.update(reply_confirm: true)
  end


  private

  def tasks_request_create_params
    params.require(:task).permit(:title, :details, :client, :contractor, :task_status, :progress, :request_reply, :start, :end_at)
  end

  def tasks_request_update_params
    params.require(:task).permit(:title, :details, :client, :contractor, :task_status, :progress, :request_reply, :start, :end_at, :request_comment)
  end

  def update_tasks_request_reply_params
    params.permit(request_tasks: %i[request_reply request_comment reply_confirm])[:request_tasks]
  end
end

app/helpers/tasks_request_helper.rb
module TasksRequestHelper
end

app/views/tasks_request/_edit.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
    <% if @btn_status != 're_request' %>
      <h5 class="modal-title">タスク情報編集</h5>
    <% else %>
      <h5 class="modal-title">タスク依頼（履歴）</h5>
    <% end %>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_with(model: @task, url: user_tasks_request_path(@user.id, @task.id), local: true, method: :patch) do |f| %>
      <div class="modal-body">
        <div class="box-title">
          <%= f.label :title, "件名", class: "form-control-label" %>
          <%= f.text_field :title, class: "form-control", placeholder: "最大20文字", maxlength: 20, required: true %>
        </div>

        <div class="box-details">
          <%= f.label :details, "詳細" %>
          <%= f.text_area :details, class: "form-control" %>
        </div>

        <div class="date-start-end">
          <div class="row">
            <div class="col-6 box-start">
              <%= f.label :start, "開始日（予定）" %>
              <div class="input-group date" id="datePicker-start" data-target-input="nearest">
              <%= f.text_field :start, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-start"}, required: true %>
                <div class="input-group-append" data-target="#datePicker-start" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
            </div>
            <div class="col-6 box-end">
              <%= f.label :end_at, "完了日（予定）" %>
              <div class="input-group date" id="datePicker-end" data-target-input="nearest">
              <%= f.text_field :end_at, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-end"}, required: true %>
                <div class="input-group-append" data-target="#datePicker-end" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="select-status-progress-request">
          <div class="box-task_status">
            <%= f.label :task_status, "状態" %>
            <%= f.select(:task_status, [["未完了", "未完了"], ["完了", "完了"]], {include_blank: "選択して下さい"}, class: 'form-control select', required: true) if @btn_status != 're_request' %>
            <%= f.select(:task_status, [["未完了", "未完了"], ["完了", "完了"]], {include_blank: "選択して下さい", selected: "未完了"}, class: 'form-control select', required: true) if @btn_status == 're_request' %>
          </div>
          <div class="box-progress">
            <%= f.label :progress, "進捗状況" %>
            <%= f.number_field :progress, min: 0, class: "form-control number", required: true if @btn_status != 're_request' %>
            <%= f.number_field :progress, min: 0, :value => 0, class: "form-control number", required: true if @btn_status == 're_request' %>
          </div>
          <span class="align-self-center">%</span>
          <div class="box-request">
            <%= f.label :contractor, "依頼先" %>
            <%= f.collection_select(:contractor, @users, :id, :name, {include_blank: "選択して下さい", selected: "#{@task.contractor}"}, {class: 'form-control', required: true}) %>
            <%= f.hidden_field :client, :value => @user.id %>
            <%= f.hidden_field :request_reply, :value => "未返答" %>
            <%= f.hidden_field :request_comment, :value => "" %>
            <%= f.hidden_field :reply_confirm, :value => false %>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">
          キャンセル
        </button>
        <% if @btn_status != 're_request' %>
          <%= f.submit "変更する", class: "btn btn-primary btn-edit" %>
        <% else %>
          <%= f.submit "依頼する", class: "btn btn-primary btn-edit" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks_request/_new.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">タスク新規依頼</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_with(model: @task, url: user_tasks_request_index_path(@user), local: true, method: :post, id: "task-form") do |f| %>
      <div class="modal-body">
        <div class="box-title">
          <%= f.label :title, "件名", class: "form-control-label" %>
          <%= f.text_field :title, class: "form-control", placeholder: "最大20文字", maxlength: 20, required: true %>
        </div>

        <div class="box-details">
          <%= f.label :details, "詳細" %>
          <%= f.text_area :details, class: "form-control" %>
        </div>

        <div class="date-start-end">
          <div class="row">
            <div class="col-6 box-start">
              <%= f.label :start, "開始日（予定）" %>
              <div class="input-group date" id="datePicker-start" data-target-input="nearest">
              <%= f.text_field :start, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-start"}, required: true %>
                <div class="input-group-append" data-target="#datePicker-start" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
            </div>
            <div class="col-6 box-end">
              <%= f.label :end_at, "完了日（予定）" %>
              <div class="input-group date" id="datePicker-end" data-target-input="nearest">
              <%= f.text_field :end_at, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-end"}, required: true %>
                <div class="input-group-append" data-target="#datePicker-end" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="select-status-progress-request">
          <div class="box-task_status">
            <%= f.label :task_status, "状態" %>
            <%= f.select(:task_status, [["未完了", "未完了"], ["完了", "完了"]], {include_blank: "選択して下さい"}, class: 'form-control select', required: true) %>
          </div>
          <div class="box-progress">
            <%= f.label :progress, "進捗状況" %>
            <%= f.number_field :progress, min: 0, class: "form-control number", required: true %>
          </div>
          <span class="align-self-center">%</span>
          <div class="box-request">
            <%= f.label :contractor, "依頼先" %>
            <%= f.collection_select(:contractor, @users, :id, :name, {include_blank: "選択して下さい", selected: "選択して下さい"}, {class: 'form-control', required: true}) %>
            <%= f.hidden_field :client, :value => @user.id %>
            <%= f.hidden_field :request_reply, :value => "未返答" %>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">
          キャンセル
        </button>
        <%= f.submit "依頼する", class: "btn btn-primary btn-new", id: "task-create" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks_request/_show.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">タスク詳細</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_with(model: @task, url: user_task_path(@task.user_id, @task.id), local: true, method: :patch) do |f| %>
      <div class="modal-body">
        <div class="box-title">
          <%= f.label :title, "件名", class: "form-control-label" %>
          <%= f.text_field :title, class: "form-control", placeholder: "最大20文字", maxlength: 20, disabled: true %>
        </div>

        <div class="box-details">
          <%= f.label :details, "詳細" %>
          <%= f.text_area :details, class: "form-control", disabled: true %>
        </div>

          <div class="date-start-end">
            <div class="row">
              <div class="col-6 box-start">
                <%= f.label :start, "開始日（予定）" %>
                <div class="input-group date" id="datePicker-start" data-target-input="nearest">
                <%= f.text_field :start, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-start"}, disabled: true %>
                  <div class="input-group-append" data-target="#datePicker-start" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar" readonly="readonly"></i></div>
                  </div>
                </div>
              </div>
              <div class="col-6 box-end">
                <%= f.label :end_at, "完了日（予定）" %>
                <div class="input-group date" id="datePicker-end" data-target-input="nearest">
                <%= f.text_field :end_at, class: "form-control datetimepicker-input", data: {toggle: "datetimepicker", target: "#datePicker-end"}, disabled: true %>
                  <div class="input-group-append" data-target="#datePicker-end" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar" readonly="readonly"></i></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        <div class="select-status-progress-request">
          <div class="box-task_status">
            <%= f.label :task_status, "状態" %>
            <%= f.select(:task_status, [["未完了", "未完了"], ["完了", "完了"]], {include_blank: "選択して下さい"}, class: 'form-control select', disabled: true) %>
          </div>
          <div class="box-progress">
            <%= f.label :progress, "進捗状況" %>
            <%= f.number_field :progress, min: 0, class: "form-control number", disabled: true %>
          </div>
          <span class="align-self-center">%</span>

            <div class="box-request">
              <%= f.label :user_id, "依頼先" %>
              <%= f.select(:contractor, [["#{@contractor.name}", "#{@contractor.id}"], ["#{@contractor.name}", "#{@contractor.id}"]], {include_blank: "選択して下さい"}, class: 'form-control', disabled: true) %>
            </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">
          戻る
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks_request/_tasks_request_reply.html.erb
<div class="modal-dialog modal-dialog-fluid modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">依頼されたタスク一覧</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_tag(user_update_tasks_request_reply_path(@user), local: true, method: :patch) do %>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered table-condensed table-hover" id="table-attendances">
              <thead>
                <tr>
                  <th>件名</th>
                  <th>詳細</th>
                  <th>開始日（予定）</th>
                  <th>終了日（予定）</th>
                  <th>依頼主</th>
                  <th>依頼を承諾しますか？</th>
                  <th>依頼主へのコメント</th>
                </tr>
              </thead>
              <% @request_tasks.each do |task| %>
                <tbody>
                  <tr>
                    <%= fields_for "request_tasks[]", task do |request_tasks|%>
                      <% client = User.find(task.client) %>
                      <td><%= task.title %></td>
                      <td><%= task.details %></td>
                      <td><%= task.start %></td>
                      <td><%= task.end_at %></td>
                      <td><%= client.name %></td>
                      <td>
                        <div class="task-radio-button">
                          <%= request_tasks.radio_button :request_reply, :承諾 %>
                          <%= request_tasks.label :request_reply, "はい", value: "承諾" %>

                          <%= request_tasks.radio_button :request_reply, :拒否 %>
                          <%= request_tasks.label :request_reply, "いいえ", value: "拒否" %>
                        </div>
                      </td>
                      <td>
                        <%= request_tasks.text_field :request_comment, class: "form-control"%>
                      </td>
                      <%= request_tasks.hidden_field :reply_confirm, :value => false %>
                    <% end %>
                  </tr>
                </tbody>
              <% end %>
            </table>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-cancel" data-dismiss="modal">
          キャンセル
        </button>
        <%= submit_tag "返信する", class: "btn btn-primary btn-edit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks_request/_tasks_request_reply_confirm.html.erb
<div class="modal-dialog modal-dialog-fluid modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">依頼タスク返信一覧</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <table class="table table-bordered table-condensed table-hover" id="table-attendances">
            <thead>
              <tr>
                <th>件名</th>
                <th>詳細</th>
                <th>開始日（予定）</th>
                <th>終了日（予定）</th>
                <th>依頼先</th>
                <th>返答</th>
                <th>コメント（依頼先）</th>
              </tr>
            </thead>
            <% @reply_tasks.each do |task| %>
              <% contractor = User.find(task.contractor) %>
              <tbody>
                <tr>
                  <td><%= task.title %></td>
                  <td><%= task.details %></td>
                  <td><%= task.start %></td>
                  <td><%= task.end_at %></td>
                  <td><%= contractor.name %></td>
                  <td><%= task.request_reply %></td>
                  <td><%= task.request_comment %></td>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks_request/_tasks_request_table.html.erb
<tbody>
  <tr>
    <td><%= task.title %></td>
    <td><%= l(task.start, format: :long) %></td>
    <td><%= l(task.end_at, format: :long) %></td>
    <td><%= task.progress %>%</td>
    <td><%= User.find(task.contractor).name %></td>
    <td><%= task.request_reply %></td>
    <td><%= task.request_comment %></td>
    <td>
      <div class="task-table-buns">
        <% if task.request_reply == '拒否'%>
          <%= link_to "再依頼", edit_user_tasks_request_path(@user.id, task.id, btn_status: 're_request'), remote: true, class: "btn btn-primary btn-sm" %>
        <% else %>
          <%= link_to "編集", edit_user_tasks_request_path(@user.id, task.id), remote: true, class: "btn btn-primary btn-sm" %>
        <% end %>
        <% if (task.client == task.user_id) || (task.client == 0) %>
          <%= link_to "削除", user_tasks_request_path(@user.id, task.id), method: :delete,data: { confirm: "#{task.title}を削除してよろしいですか？" }, class: "btn btn-danger btn-sm" %>
        <% end %>
        <%= link_to "詳細", user_tasks_request_path(@user.id, task.id), remote: true, class: "btn btn-primary btn-sm" %>
      </div>
    </td>
  </tr>
</tbody>

app/views/tasks_request/edit.js.erb
$("#task-request-edit").html("<%= escape_javascript(render 'edit') %>");
$("#task-request-edit").modal("show");

$(document).ready(function () {
  $('#datePicker-start').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
  $('#datePicker-end').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
});

app/views/tasks_request/index.html.erb
<% provide(:title, "All_tasks_request") %>
<div class="tasks-container container-fluid">
  <div class="title"><h1>タスク一覧（依頼）</h1></div>
  <div class="row">
    <div class="task-btn col-6"">
      <div class="task-btns">
        <%= link_to "タスク登録（新規）", new_user_task_path(@user), remote: true, class: "btn btn-primary btn-sm" %>
        <%= link_to "タスク登録（履歴）", user_tasks_all_history_path(@user), class: "btn btn-primary btn-sm" %>
        <%= link_to "未完了", user_tasks_path(@user, btn_status: "incomplete"), class: "btn btn-primary btn-sm" %>
        <%= link_to "完了", user_tasks_path(@user, btn_status: "completed"), class: "btn btn-primary btn-sm" %>
      </div>
    </div>
    <div class="col-6">
      <div class="user-search float-right">
        <a id="search">タスク名検索</a>
        <%= form_with url: user_tasks_request_all_history_path(@user), method: :get, local: true do |form| %>
          <%= form.text_field :search, id: "search-box", placeholder: "キーワードを入力" %>
          <%= form.submit "検索", id: "search-btn", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-condensed table-hover" id="table-users">
        <thead>
          <tr>
            <th>件名</th>
            <th>開始日（予定）</th>
            <th>完了日（予定）</th>
            <th>進捗度</th>
            <th>依頼先</th>
            <th>返答</th>
            <th>コメント（依頼先）</th>
            <th></th>
          </tr>
        </thead>
        <%= render partial: 'tasks_request_table', collection: @tasks, as: :task %>
      </table>
      <% if @tasks.blank?%>
        <div class="task-none">
          <a>該当のタスクはありません。</a>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--タスク情報編集用モーダルウインドウ表示-->
<div class="modal fade" id="task-request-edit" tabindex="-1" role="dialog" aria-labelledby="usereditModalLabel" aria-hidden="true"></div>
<!--タスク詳細用モーダルウインドウ表示-->
<div class="modal fade" id="task-request-show" tabindex="-1" role="dialog" aria-labelledby="usereditModalLabel" aria-hidden="true"></div>

app/views/tasks_request/new.js.erb
$("#task-request-new").html("<%= escape_javascript(render 'new') %>");
$("#task-request-new").modal("show");

$(document).ready(function () {
  $('#datePicker-start').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
  $('#datePicker-end').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
});

app/views/tasks_request/show.js.erb
$("#task-request-show").html("<%= escape_javascript(render 'show') %>");
$("#task-request-show").modal("show");

$(document).ready(function () {
  $('#datePicker-start').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
  $('#datePicker-end').datetimepicker({locale: 'ja', dayViewHeaderFormat: 'YYYY年M月' ,format: 'YYYY/MM/DD'});
});

app/views/tasks_request/tasks_request_all_history.html.erb
<% provide(:title, 'All_tasks_history') %>
<div class="tasks-container container-fluid">
  <div class="title">
    <% if params[:search].present? %>
      <h1>検索結果</h1>
    <% else %>
      <h1>タスク履歴（再依頼）</h1>
    <% end %>
  </div>
  <div class="row">
    <div class="task-btn col-6">
      <div class="task-btns">
        <%= link_to "タスク登録（新規）", new_user_task_path(@user), remote: true, class: "btn btn-primary btn-sm" %>
        <%= link_to "タスク登録（履歴）", user_tasks_all_history_path(@user), class: "btn btn-primary btn-sm" %>
        <%= link_to "未完了", user_tasks_path(@user, btn_status: "incomplete"), class: "btn btn-primary btn-sm" %>
        <%= link_to "完了", user_tasks_path(@user, btn_status: "completed"), class: "btn btn-primary btn-sm" %>
        <% if current_user.admin? %>
          <%= link_to "依頼", user_tasks_request_index_path(@user), class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div class="user-search float-right">
        <a id="search">タスク名検索</a>
        <%= form_with url: user_tasks_request_all_history_path(@user), method: :get, local: true do |form| %>
          <%= form.text_field :search, id: "search-box", placeholder: "キーワードを入力" %>
          <%= form.submit "検索", id: "search-btn", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-condensed table-hover" id="table-users">
        <thead>
          <tr>
            <th>件名</th>
            <th>詳細</th>
            <th>開始日（予定）</th>
            <th>完了日（予定）</th>
            <th>担当者（前回）</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @tasks.each do |task| %>
            <tr>
              <td><%= task.title %></td>
              <td><%= task.details %></td>
              <td><%= task.start %></td>
              <td><%= task.end_at %></td>
              <% if task.contractor != 0 %>
                <td><%= User.find(task.contractor).name %></td>
              <% else %>
                <td><%= User.find(task.user_id).name %></td>
              <% end %>
              <td>
                <%= link_to "依頼", edit_user_tasks_request_path(@user.id, task.id, btn_status: "re_request"), remote: true, class: "btn btn-primary btn-sm", id: "task-request-btn" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="users-paginate">
        <% if @tasks.present?%>
          <div class="paginate">
            <%= paginate @tasks %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--タスク情報編集用モーダルウインドウ表示-->
<div class="modal fade" id="task-request-edit" tabindex="-1" role="dialog" aria-labelledby="usereditModalLabel" aria-hidden="true"></div>

app/views/tasks_request/tasks_request_reply.js.erb
$("#tasks-request-reply").html("<%= escape_javascript(render 'tasks_request_reply') %>");
$("#tasks-request-reply").modal("show");

app/views/tasks_request/tasks_request_reply_confirm.js.erb
$("#tasks_request_reply_confirm").html("<%= escape_javascript(render 'tasks_request_reply_confirm') %>");
$("#tasks_request_reply_confirm").modal("show");

$("#tasks_request_reply_confirm,.close").unbind().click(function(){
	window.location.reload();
});